<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE nameTable [
<!ELEMENT nameTable (nameTableEntry+)>
<!ELEMENT nameTableEntry (localizedName+)>
<!ELEMENT localizedName (#PCDATA)>
<!ATTLIST nameTableEntry nameTypeID CDATA #REQUIRED
	nameTypeName CDATA #IMPLIED>
<!ATTLIST nameTable fontName CDATA #IMPLIED>
<!ATTLIST localizedName platformID CDATA #REQUIRED
	platformName CDATA #IMPLIED
	scriptID CDATA #REQUIRED
	scriptName CDATA #IMPLIED
	languageID CDATA #REQUIRED
	languageName CDATA #IMPLIED
	isRawHex CDATA #IMPLIED
>
]>


<!--

	Data generated 	Thu Jan  9 12:32:34 2020

	Generated by ftxdumperfuser build 356,
		FontToolbox.framework build 332

	Font full name: 'DrukFontV13'
	Font PostScript name: 'DrukFontV13'

-->


<nameTable>
	<nameTableEntry nameTypeID="1" nameTypeName="Family">
		<localizedName platformID="1" platformName="Macintosh" scriptID="0" scriptName="Roman" languageID="0" languageName="English" isRawHex="NO">Druk Tibetan</localizedName>
		<localizedName platformID="3" platformName="Microsoft" scriptID="1" scriptName="Unicode" languageID="1033" languageName="English, United States" isRawHex="NO">Druk Tibetan</localizedName>
	</nameTableEntry>
	<nameTableEntry nameTypeID="2" nameTypeName="Style">
		<localizedName platformID="1" platformName="Macintosh" scriptID="0" scriptName="Roman" languageID="0" languageName="English" isRawHex="NO">Regular</localizedName>
		<localizedName platformID="3" platformName="Microsoft" scriptID="1" scriptName="Unicode" languageID="1033" languageName="English, United States" isRawHex="NO">Regular</localizedName>
	</nameTableEntry>
	<nameTableEntry nameTypeID="3" nameTypeName="Unique">
		<localizedName platformID="1" platformName="Macintosh" scriptID="0" scriptName="Roman" languageID="0" languageName="English" isRawHex="NO">14.0;APPL;DrukFontV14;2005;FLVI-612</localizedName>
		<localizedName platformID="3" platformName="Microsoft" scriptID="1" scriptName="Unicode" languageID="1033" languageName="English, United States" isRawHex="NO">14.0;APPL;DrukFontV14;2005;FLVI-612</localizedName>
	</nameTableEntry>
	<nameTableEntry nameTypeID="4" nameTypeName="Full">
		<localizedName platformID="1" platformName="Macintosh" scriptID="0" scriptName="Roman" languageID="0" languageName="English" isRawHex="NO">Druk Tibetan</localizedName>
		<localizedName platformID="3" platformName="Microsoft" scriptID="1" scriptName="Unicode" languageID="1033" languageName="English, United States" isRawHex="NO">Druk Tibetan</localizedName>
	</nameTableEntry>
	<nameTableEntry nameTypeID="5" nameTypeName="Version">
		<localizedName platformID="1" platformName="Macintosh" scriptID="0" scriptName="Roman" languageID="0" languageName="English" isRawHex="NO">14.0</localizedName>
		<localizedName platformID="3" platformName="Microsoft" scriptID="1" scriptName="Unicode" languageID="1033" languageName="English, United States" isRawHex="NO">14.0</localizedName>
	</nameTableEntry>
	<nameTableEntry nameTypeID="6" nameTypeName="PostScript">
		<localizedName platformID="1" platformName="Macintosh" scriptID="0" scriptName="Roman" languageID="0" languageName="English" isRawHex="NO">DrukFontV14</localizedName>
		<localizedName platformID="3" platformName="Microsoft" scriptID="1" scriptName="Unicode" languageID="1033" languageName="English, United States" isRawHex="NO">DrukFontV14</localizedName>
	</nameTableEntry>
</nameTable>
